"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { Building2, Check, Loader2, MapPin, Search, Star } from "lucide-react";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import type { ExtractedLead } from "@/types/database";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

const schema = z.object({ query: z.string().min(2, "Informe um nicho"), location: z.string().min(2, "Informe a cidade"), limit: z.coerce.number().int().min(1).max(20) });
type SearchData = z.infer<typeof schema>;

export function ExtractorClient() {
  const [results, setResults] = useState<ExtractedLead[]>([]); const [selected, setSelected] = useState<Set<string>>(new Set()); const [error, setError] = useState<string | null>(null); const [importing, setImporting] = useState(false); const [success, setSuccess] = useState<string | null>(null);
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<SearchData>({ resolver: zodResolver(schema), defaultValues: { query: "Academias", location: "São Paulo, SP", limit: 10 } });
  async function search(data: SearchData) { setError(null); setSuccess(null); const response = await fetch("/api/extract", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const json = await response.json() as { leads?: ExtractedLead[]; error?: string }; if (!response.ok) { setError(json.error ?? "Falha na busca"); return; } setResults(json.leads ?? []); setSelected(new Set((json.leads ?? []).map((lead) => lead.externalId))); }
  function toggle(id: string) { setSelected((current) => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next; }); }
  async function importLeads() { setImporting(true); setError(null); const leads = results.filter((lead) => selected.has(lead.externalId)); const response = await fetch("/api/leads", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ leads }) }); const json = await response.json() as { imported?: number; error?: string }; setImporting(false); if (!response.ok) { setError(json.error ?? "Falha ao importar"); return; } setSuccess(`${json.imported ?? leads.length} leads importados para o pipeline.`); }
  return <div className="space-y-5"><Card><CardContent className="pt-5"><form onSubmit={handleSubmit(search)} className="grid gap-4 lg:grid-cols-[1fr_1fr_130px_auto]"><label className="text-xs font-medium text-zinc-400">Termo ou nicho<Input className="mt-2" placeholder="Ex: Clínicas odontológicas" {...register("query")} />{errors.query && <span className="mt-1 block text-red-400">{errors.query.message}</span>}</label><label className="text-xs font-medium text-zinc-400">Cidade / UF<Input className="mt-2" placeholder="Ex: Curitiba, PR" {...register("location")} />{errors.location && <span className="mt-1 block text-red-400">{errors.location.message}</span>}</label><label className="text-xs font-medium text-zinc-400">Limite<Input className="mt-2" type="number" {...register("limit")} /></label><Button className="mt-auto" size="default" disabled={isSubmitting}>{isSubmitting ? <Loader2 className="h-4 w-4 animate-spin" /> : <Search className="h-4 w-4" />}Buscar leads</Button></form></CardContent></Card>
    {error && <div className="rounded-lg border border-red-500/20 bg-red-500/5 p-4 text-sm text-red-300">{error}</div>}{success && <div className="rounded-lg border border-emerald-500/20 bg-emerald-500/5 p-4 text-sm text-emerald-300">{success}</div>}
    {results.length > 0 && <Card><CardContent className="pt-5"><div className="mb-5 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="font-semibold">{results.length} empresas encontradas</h2><p className="text-xs text-zinc-500">{selected.size} selecionadas para importar</p></div><Button onClick={importLeads} disabled={!selected.size || importing}>{importing ? <Loader2 className="h-4 w-4 animate-spin" /> : <Check className="h-4 w-4" />}Importar para o pipeline</Button></div><div className="divide-y divide-zinc-800">{results.map((lead) => <label key={lead.externalId} className="flex cursor-pointer items-center gap-4 py-4"><input type="checkbox" checked={selected.has(lead.externalId)} onChange={() => toggle(lead.externalId)} className="h-4 w-4 rounded border-zinc-700 accent-violet-500" /><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-zinc-800"><Building2 className="h-4 w-4 text-zinc-400" /></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{lead.name}</span><span className="mt-1 flex items-center gap-1 truncate text-xs text-zinc-500"><MapPin className="h-3 w-3" />{lead.address ?? "Endereço não informado"}</span></span>{lead.rating && <span className="flex items-center gap-1 text-xs font-medium text-amber-400"><Star className="h-3 w-3 fill-current" />{lead.rating}</span>}<span className="hidden text-xs text-zinc-500 md:block">{lead.phone ?? "Sem telefone"}</span></label>)}</div></CardContent></Card>}
    {!results.length && !isSubmitting && <div className="flex min-h-72 flex-col items-center justify-center rounded-xl border border-dashed border-zinc-800 text-center"><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-zinc-900"><Search className="h-6 w-6 text-zinc-600" /></span><h3 className="mt-4 text-sm font-medium">Sua próxima oportunidade começa aqui</h3><p className="mt-1 max-w-sm text-xs leading-relaxed text-zinc-600">Defina um segmento e uma região para encontrar empresas com dados públicos.</p></div>}
  </div>;
}
