"use client";

import { DndContext, DragEndEvent, DragOverlay, DragStartEvent, PointerSensor, useDroppable, useSensor, useSensors } from "@dnd-kit/core";
import { CSS } from "@dnd-kit/utilities";
import { useDraggable } from "@dnd-kit/core";
import { Bot, ExternalLink, GripVertical, Loader2, MapPin, Sparkles, Star, Trash2 } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { STATUS_CONFIG } from "@/lib/constants";
import { buildGoogleMapsUrl, cn } from "@/lib/utils";
import { LEAD_STATUSES, type Lead, type LeadStatus } from "@/types/database";
import { Button } from "@/components/ui/button";

function LeadCard({ lead, overlay = false, onQualify, onDelete, qualifying, deleting }: { lead: Lead; overlay?: boolean; onQualify?: (lead: Lead) => void; onDelete?: (lead: Lead) => void; qualifying?: boolean; deleting?: boolean }) {
  const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({ id: lead.id, data: { lead } });
  const style = transform ? { transform: CSS.Translate.toString(transform) } : undefined;
  const googleMapsUrl = lead.google_maps_url ?? buildGoogleMapsUrl(lead.name, lead.address);
  return <article ref={setNodeRef} style={style} className={cn("rounded-xl border border-zinc-800 bg-zinc-900 p-3.5 shadow-lg transition", isDragging && !overlay && "opacity-30", overlay && "w-72 rotate-2 border-violet-500/40 shadow-2xl shadow-violet-950")}>
    <div className="flex items-start gap-2"><button aria-label="Arrastar lead" {...listeners} {...attributes} className="mt-0.5 cursor-grab text-zinc-700 hover:text-zinc-400"><GripVertical className="h-4 w-4" /></button><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><Link href={`/leads/${lead.id}`} className="truncate text-sm font-semibold hover:text-violet-300">{lead.name}</Link>{!overlay && <button type="button" aria-label={`Apagar ${lead.name}`} title="Apagar lead" onClick={() => onDelete?.(lead)} disabled={deleting} className="flex h-7 w-7 shrink-0 items-center justify-center rounded-md text-zinc-600 transition hover:bg-red-500/10 hover:text-red-400 disabled:opacity-50">{deleting ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Trash2 className="h-3.5 w-3.5" />}</button>}</div><p className="mt-1 flex items-center gap-1 truncate text-[11px] text-zinc-500"><MapPin className="h-3 w-3" />{lead.address ?? "Local não informado"}</p>{!overlay && <a href={googleMapsUrl} target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1 text-[11px] font-medium text-blue-400 transition hover:text-blue-300 hover:underline">Ver no Google <ExternalLink className="h-3 w-3" /></a>}</div></div>
    <div className="mt-3 flex items-center gap-2">{lead.rating && <span className="flex items-center gap-1 rounded-md bg-amber-500/10 px-2 py-1 text-[10px] font-semibold text-amber-400"><Star className="h-3 w-3 fill-current" />{lead.rating}</span>}{lead.ai_score !== null && <span className={cn("ml-auto rounded-full px-2 py-1 text-[10px] font-bold", lead.ai_score >= 80 ? "bg-emerald-500/10 text-emerald-400" : lead.ai_score >= 60 ? "bg-amber-500/10 text-amber-400" : "bg-red-500/10 text-red-400")}>Score {lead.ai_score}</span>}</div>
    {lead.ai_summary && <p className="mt-3 line-clamp-2 text-[11px] leading-relaxed text-zinc-500">{lead.ai_summary}</p>}
    {!overlay && <div className="mt-3 border-t border-zinc-800 pt-3"><Button variant="ghost" size="sm" className="w-full text-violet-400 hover:text-violet-300" onClick={() => onQualify?.(lead)} disabled={qualifying}>{qualifying ? <Loader2 className="h-3 w-3 animate-spin" /> : <Sparkles className="h-3 w-3" />}{lead.ai_score === null ? "Qualificar com IA" : "Requalificar"}</Button></div>}
  </article>;
}

function Column({ status, leads, onQualify, onDelete, qualifyingId, deletingId }: { status: LeadStatus; leads: Lead[]; onQualify: (lead: Lead) => void; onDelete: (lead: Lead) => void; qualifyingId: string | null; deletingId: string | null }) {
  const { isOver, setNodeRef } = useDroppable({ id: status }); const config = STATUS_CONFIG[status];
  return <section ref={setNodeRef} className={cn("flex w-[290px] shrink-0 flex-col rounded-xl border bg-zinc-950/50 transition", config.color, isOver && "border-violet-400 bg-violet-500/5")}><header className="flex items-center gap-2 border-b border-zinc-800/70 p-3"><span className={`h-2 w-2 rounded-full ${config.dot}`} /><h2 className="text-xs font-semibold uppercase tracking-wide text-zinc-400">{config.label}</h2><span className="ml-auto rounded-md bg-zinc-800 px-2 py-0.5 text-[10px] font-bold text-zinc-500">{leads.length}</span></header><div className="min-h-40 flex-1 space-y-3 p-3">{leads.map((lead) => <LeadCard key={lead.id} lead={lead} onQualify={onQualify} onDelete={onDelete} qualifying={qualifyingId === lead.id} deleting={deletingId === lead.id} />)}{!leads.length && <div className="flex h-28 items-center justify-center rounded-lg border border-dashed border-zinc-800 text-[11px] text-zinc-700">Arraste um lead para cá</div>}</div></section>;
}

export function PipelineBoard({ initialLeads, demo }: { initialLeads: Lead[]; demo: boolean }) {
  const [leads, setLeads] = useState(initialLeads); const [active, setActive] = useState<Lead | null>(null); const [qualifyingId, setQualifyingId] = useState<string | null>(null); const [deletingId, setDeletingId] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 8 } }));
  async function moveLead(event: DragEndEvent) { setActive(null); if (!event.over) return; const id = String(event.active.id); const target = String(event.over.id) as LeadStatus; if (!LEAD_STATUSES.includes(target)) return; const before = leads; setLeads((list) => list.map((lead) => lead.id === id ? { ...lead, status: target } : lead)); if (demo) return; const response = await fetch(`/api/leads/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: target }) }); if (!response.ok) { setLeads(before); setMessage("Não foi possível mover o lead."); } }
  async function qualify(lead: Lead) { if (demo) { setLeads((list) => list.map((item) => item.id === lead.id ? { ...item, ai_score: 88, ai_summary: "Empresa com boa reputação local e sinais claros de oportunidade comercial.", ai_pitch: "Sua reputação já chama atenção. Podemos transformar essa presença em uma fonte previsível de novos clientes.", status: "qualificado" } : item)); return; } setQualifyingId(lead.id); setMessage(null); const response = await fetch("/api/qualify", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ leadId: lead.id }) }); const json = await response.json() as { lead?: Lead; error?: string }; setQualifyingId(null); if (!response.ok || !json.lead) { setMessage(json.error ?? "Não foi possível qualificar o lead."); return; } setLeads((list) => list.map((item) => item.id === lead.id ? json.lead! : item)); }
  async function deleteLead(lead: Lead) { if (!window.confirm(`Apagar o lead “${lead.name}”? Esta ação não pode ser desfeita.`)) return; setDeletingId(lead.id); setMessage(null); if (demo) { setLeads((list) => list.filter((item) => item.id !== lead.id)); setDeletingId(null); return; } const response = await fetch(`/api/leads/${lead.id}`, { method: "DELETE" }); const json = await response.json() as { error?: string }; setDeletingId(null); if (!response.ok) { setMessage(json.error ?? "Não foi possível apagar o lead."); return; } setLeads((list) => list.filter((item) => item.id !== lead.id)); }
  return <>{message && <div className="mb-4 rounded-lg border border-red-500/20 bg-red-500/5 p-3 text-sm text-red-300">{message}</div>}<DndContext sensors={sensors} onDragStart={(event: DragStartEvent) => setActive((event.active.data.current?.lead as Lead | undefined) ?? null)} onDragEnd={moveLead} onDragCancel={() => setActive(null)}><div className="scrollbar-thin flex gap-4 overflow-x-auto pb-5">{LEAD_STATUSES.map((status) => <Column key={status} status={status} leads={leads.filter((lead) => lead.status === status)} onQualify={qualify} onDelete={deleteLead} qualifyingId={qualifyingId} deletingId={deletingId} />)}</div><DragOverlay>{active ? <LeadCard lead={active} overlay /> : null}</DragOverlay></DndContext><div className="mt-2 flex items-center gap-2 text-xs text-zinc-600"><Bot className="h-3.5 w-3.5" />A IA usa a chave configurada na sua conta.<Link href="/configuracoes/integracoes" className="flex items-center gap-1 text-violet-400">Configurar <ExternalLink className="h-3 w-3" /></Link></div></>;
}
